### ISSUE TITLE
How to build for production use

### ISSUE THREAD

**Issue by xe1os** [FlowingSPDG/Got5#40]
Hi! @FlowingSPDG

First of all kudos to your work on Get5/Got5 built with golang.

I got few queries to ask on this project of yours.

1. Does this have english lang support?
2. Is this ready for production use?
3. Does this build give single executable file?
4. Is there are wiki on how to build this project?

Thanks again.

**Comment by FlowingSPDG** [comment]
Hi @xe1os ! thank you for interested in this project!
Here's answers of your questions:

1. Since I'm a japanese guy, comments in codes are mostly in Japanese. But I try to write it in English as well. Also, this is a framework, not a single working project like get5-web. so it depends on your implemention.
2. I do use this framework for my side-work project, but I cannot promise there's no issue for e.g. security, I want you to decide it by yourself by reading code.
3. No, but you can get single executable by compiling example projects in https://github.com/FlowingSPDG/Got5/tree/main/examples.
4. No, but mostly you only need Go to compile executable. e.g. ``cd examples/logger/cmd/main.go && go build main.go``. Make sure you have latest Go or later than 1.18.

Hope this helps!

**Comment by FlowingSPDG** [comment]
Please re-open this issue if you need more support of answer! :)

**Comment by xe1os** [comment]
Can you please upload compiled exe for me to check and test.

Though i tried compiling single executable files i was still getting error `Cannot GET `/`` error in [http://127.0.0.1:3000/](url)

**Comment by FlowingSPDG** [comment]
What kind of example do you need? its just a libray, not software or service. Got5 makes you develop get5 based system easier.

**Comment by xe1os** [comment]
> What kind of example do you need? its just a libray, not software or service. Got5 makes you develop get5 based system easier.

It will help if you can share the binaries that you have built.

**Comment by xe1os** [comment]
I'm looking for standalone binaries that can be  used for local/LAN hosting purpose on Windows system.

**Comment by FlowingSPDG** [comment]
> > What kind of example do you need? its just a libray, not software or service. Got5 makes you develop get5 based system easier.
> 
> It will help if you can share the binaries that you have built.

Check example directory for more detail.



> I'm looking for standalone binaries that can be used for local/LAN hosting purpose on Windows system.

Again Got5 is not a system. Its a library that can be used as base library to built get5 integrated system.
